import { DM_Sans } from "next/font/google";
import "./globals.css";

const DmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DmSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
